server {
    listen 8080;
    root ./www;
    client_max_body_size 1000000;

    location / {
        methods GET;
        index index.html;
    }

    location /upload {
        methods POST;
        upload on;
        upload_path ./uploads;
    }
}