server {
    listen 8080;
    root ./sandbox/upload_demo/www;
    client_max_body_size 10000000;

    error_page 404 ./sandbox/upload_demo/www/404.html;

    location / {
        methods GET;
        index index.html;
    }

    location /uploads {
        methods GET POST DELETE;
        root ./sandbox/upload_demo/uploads;
        autoindex on;
        upload on;
        upload_path ./sandbox/upload_demo/uploads;
    }
}
